language: node_js
sudo: false
cache:
  directories:
  - node_modules
git:
  depth: 3

env:
  - NODE_ENV=test

node_js:
  - "4"
  - "5"
  - "6"

before_script:
  npm run lint

after_script:
  mkdir .nyc_output && npm run coveralls
